import type { Jam } from "./types";

/**
 * ~10 jams mock que cubren TODAS las variantes de tarjeta y de filtro:
 * premio grande, featured, convocatoria LatAm en español (Cultura PE),
 * sólo-deadline sin fecha de inicio, IA prohibida, IA permitida, en curso,
 * y modalidades online / presencial / híbrida / sin definir.
 *
 * Fechas ancladas a julio–agosto 2026 para que las cuentas regresivas al
 * deadline sean reales respecto de la fecha actual. Nada de red aquí.
 */
export const MOCK_JAMS: Jam[] = [
  {
    source: "devpost",
    sourceId: "devpost-ai-games-hackathon-2026",
    url: "https://devpost.com/hackathons/ai-games-hackathon-2026",
    title: "AI Games Hackathon 2026",
    hosts: [{ name: "DevNetwork", url: "https://devpost.com" }],
    startAt: "2026-06-30T00:00:00.000Z",
    endAt: "2026-07-03T09:00:00.000Z",
    durationDays: 3,
    theme: null,
    tags: ["IA", "Web", "48h"],
    languages: ["en"],
    hasPrize: true,
    prizeSummary: "$10.000 USD · +créditos cloud",
    prizeValueUsd: 10000,
    aiPolicy: "allowed",
    mode: "online",
    participants: 1940,
    country: null,
    ranked: false,
    featured: false,
    enrichmentConfidence: 0.9,
  },
  {
    source: "ludumdare",
    sourceId: "ludumdare-56",
    url: "https://ldjam.com/events/ludum-dare/56",
    title: "Ludum Dare 56 — Tiny Creatures",
    hosts: [{ name: "Ludum Dare", url: "https://ldjam.com" }],
    startAt: "2026-07-10T18:00:00.000Z",
    endAt: "2026-07-13T18:00:00.000Z",
    durationDays: 3,
    theme: "Tiny Creatures",
    tags: ["Tema sorpresa", "Compo/Jam", "Ranking"],
    languages: ["es", "en"],
    hasPrize: false,
    prizeSummary: null,
    prizeValueUsd: null,
    aiPolicy: "allowed",
    mode: "online",
    participants: 4812,
    country: null,
    ranked: true,
    featured: true,
    enrichmentConfidence: 0.95,
  },
  {
    source: "itch",
    sourceId: "itch-pixel-horror-jam-2026",
    url: "https://itch.io/jam/pixel-horror-jam-2026",
    title: "Pixel Horror Jam 2026",
    hosts: [{ name: "Cripta Estudio" }],
    startAt: "2026-07-05T00:00:00.000Z",
    endAt: "2026-07-24T23:59:00.000Z",
    durationDays: 19,
    theme: "Terror analógico",
    tags: ["Terror", "Pixel art", "Narrativa"],
    languages: ["es"],
    hasPrize: true,
    prizeSummary: "$2.000 USD · Bolsa · 4 categorías",
    prizeValueUsd: 2000,
    aiPolicy: "banned",
    mode: "online",
    participants: 318,
    country: null,
    ranked: true,
    featured: false,
    enrichmentConfidence: 0.72,
  },
  {
    source: "cultura-pe",
    sourceId: "cultura-pe-estimulos-videojuegos-2026",
    url: "https://estimuloseconomicos.cultura.gob.pe/",
    title: "Estímulos Económicos para Videojuegos — Cultura PE 2026",
    hosts: [
      {
        name: "Ministerio de Cultura del Perú",
        url: "https://www.gob.pe/cultura",
      },
    ],
    startAt: null,
    endAt: "2026-08-30T23:59:00.000Z",
    durationDays: null,
    theme: null,
    tags: ["LatAm", "Fondo", "Cultural"],
    languages: ["es", "pt"],
    hasPrize: true,
    prizeSummary: "$8.000 USD · Financiamiento a la creación",
    prizeValueUsd: 8000,
    aiPolicy: "unknown",
    mode: "unknown",
    participants: null,
    country: "PE",
    ranked: false,
    featured: false,
    enrichmentConfidence: 0.6,
  },
  {
    source: "itch",
    sourceId: "itch-brackeys-game-jam-2026-2",
    url: "https://itch.io/jam/brackeys-13",
    title: "Brackeys Game Jam 2026.2",
    hosts: [{ name: "Brackeys" }],
    startAt: "2026-07-06T19:00:00.000Z",
    endAt: "2026-07-13T19:00:00.000Z",
    durationDays: 7,
    theme: null,
    tags: ["Comunidad", "Ranking", "Principiantes"],
    languages: ["en"],
    hasPrize: false,
    prizeSummary: null,
    prizeValueUsd: null,
    aiPolicy: "allowed",
    mode: "online",
    participants: 12400,
    country: null,
    ranked: true,
    featured: false,
    enrichmentConfidence: 0.88,
  },
  {
    source: "cultura-pe",
    sourceId: "cultura-pe-premios-playlat-2026",
    url: "https://playlat.org/premios-2026",
    title: "Premios PlayLat — Selección Oficial",
    hosts: [{ name: "PlayLat" }],
    startAt: "2026-08-01T00:00:00.000Z",
    endAt: "2026-08-01T23:59:00.000Z",
    durationDays: 1,
    theme: null,
    tags: ["Presencial", "México", "Showcase"],
    languages: ["es"],
    hasPrize: true,
    prizeSummary: "$120.000 MXN · Premios + exhibición",
    prizeValueUsd: 6000,
    aiPolicy: "unknown",
    mode: "in-person",
    participants: null,
    country: "MX",
    ranked: false,
    featured: false,
    enrichmentConfidence: 0.65,
  },
  {
    source: "itch",
    sourceId: "itch-one-room-jam",
    url: "https://itch.io/jam/one-room-jam",
    title: "One-Room Jam",
    hosts: [{ name: "Team Cabin" }],
    startAt: null,
    endAt: "2026-07-18T23:59:00.000Z",
    durationDays: null,
    theme: null,
    tags: ["Restricción", "Micro"],
    languages: ["en"],
    hasPrize: false,
    prizeSummary: null,
    prizeValueUsd: null,
    aiPolicy: "allowed",
    mode: "online",
    participants: 640,
    country: null,
    ranked: false,
    featured: false,
    enrichmentConfidence: 0.7,
  },
  {
    source: "itch",
    sourceId: "itch-godot-wild-jam-82",
    url: "https://itch.io/jam/godot-wild-jam-82",
    title: "Godot Wild Jam #82",
    hosts: [{ name: "Godot Wild Jam" }],
    startAt: "2026-06-27T00:00:00.000Z",
    endAt: "2026-07-06T20:00:00.000Z",
    durationDays: 9,
    theme: "Ecos",
    tags: ["Godot", "Comunidad", "Ranking"],
    languages: ["es", "en"],
    hasPrize: false,
    prizeSummary: null,
    prizeValueUsd: null,
    aiPolicy: "unknown",
    mode: "online",
    participants: 1300,
    country: null,
    ranked: true,
    featured: false,
    enrichmentConfidence: 0.8,
  },
  {
    source: "itch",
    sourceId: "itch-narrativa-interactiva-jam",
    url: "https://itch.io/jam/narrativa-interactiva",
    title: "Narrativa Interactiva Jam",
    hosts: [{ name: "Relato" }],
    startAt: "2026-07-08T00:00:00.000Z",
    endAt: "2026-07-22T23:59:00.000Z",
    durationDays: 14,
    theme: null,
    tags: ["Twine", "Historia", "Narrativa"],
    languages: ["es"],
    hasPrize: false,
    prizeSummary: null,
    prizeValueUsd: null,
    aiPolicy: "allowed",
    mode: "online",
    participants: 210,
    country: null,
    ranked: false,
    featured: false,
    enrichmentConfidence: 0.75,
  },
  {
    source: "devpost",
    sourceId: "devpost-xr-mixed-reality-jam-2026",
    url: "https://devpost.com/hackathons/xr-mixed-reality-jam-2026",
    title: "XR Mixed Reality Jam",
    hosts: [{ name: "XR Guild" }],
    startAt: "2026-07-09T00:00:00.000Z",
    endAt: "2026-07-16T23:59:00.000Z",
    durationDays: 7,
    theme: null,
    tags: ["XR", "Realidad mixta", "Unity"],
    languages: ["en"],
    hasPrize: true,
    prizeSummary: "$5.000 USD",
    prizeValueUsd: 5000,
    aiPolicy: "unknown",
    mode: "hybrid",
    participants: 870,
    country: "US",
    ranked: false,
    featured: false,
    enrichmentConfidence: 0.68,
  },
];
